Controllers/DoctorController.cs
using System;
using G7.Models;
using System.Collections.Generic;
using System.IO;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Web;
using System.Web.Mvc;


namespace G7.Controllers
{
    public class DoctorController : Controller
    {
        [HttpPost]
        public ActionResult CrearDoctor(DoctorObj doctor)
        {
            using (HttpClient client = new HttpClient())
            {
                string rutaApi = ConfigurationManager.AppSettings["rutaApi"] + "api/Doctor/CrearDoctor";
                string token = Session["codigoToken"]?.ToString();

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                JsonContent contenido = JsonContent.Create(doctor);

                HttpResponseMessage respuesta = client.PostAsync(rutaApi, contenido).Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    return RedirectToAction("VerDoctor", new { id = doctor.IdDoctor });
                }
                return View("Error");
            }
        }
        public ActionResult VerDoctor(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string rutaApi = ConfigurationManager.AppSettings["rutaApi"] + "api/Doctor/VerDoctor?id=" + id;
                string token = Session["codigoToken"]?.ToString();

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                HttpResponseMessage respuesta = client.GetAsync(rutaApi).Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    DoctorObj doctor = respuesta.Content.ReadAsAsync<DoctorObj>().Result;
                    return View(doctor);
                }
                return View("Error");
            }
        }
        [HttpPost]
        public ActionResult BuscarDoctor(string nombre)
        {
            using (HttpClient client = new HttpClient())
            {
                string rutaApi = ConfigurationManager.AppSettings["rutaApi"] + "api/Doctor/BuscarDoctor?nombre=" + nombre;
                string token = Session["codigoToken"]?.ToString();

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                HttpResponseMessage respuesta = client.GetAsync(rutaApi).Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    List<DoctorObj> doctores = respuesta.Content.ReadAsAsync<List<DoctorObj>>().Result;
                    return View(doctores);
                }
                return View("Error");
            }
        }

    }
}

Views/Doctor/BuscarDoctor.cshtml
@{
    ViewBag.Title = "BuscarDoctor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>BuscarDoctor</h2>

Views/Doctor/CrearDoctor.cshtml
@model G7.Models.DoctorObj

@{
    ViewBag.Title = "Crear Doctor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Crear Doctor</h2>
    <hr />


    @using (Html.BeginForm("CrearDoctor", "Doctor", FormMethod.Post))
    {
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label for="idDoctor">ID Doctor:</label>
                    @Html.TextBoxFor(model => model.IdDoctor, new { @class = "form-control", placeholder = "Ingrese el ID del doctor", required = "required" })
                    <div class="invalid-feedback">
                        Por favor, ingrese el ID del doctor.
                    </div>
                </div>
                <div class="form-group">
                    <label for="idUsuario">ID Usuario:</label>
                    @Html.TextBoxFor(model => model.IdUsuario, new { @class = "form-control", placeholder = "Ingrese el ID del usuario", required = "required" })
                    <div class="invalid-feedback">
                        Por favor, ingrese el ID del usuario.
                    </div>
                </div>
                <div class="form-group">
                    <label for="SalarioBruto">Salario Bruto:</label>
                    @Html.TextBoxFor(model => model.SalarioBruto, new { @class = "form-control", placeholder = "Ingrese el salario bruto", required = "required" })
                    <div class="invalid-feedback">
                        Por favor, ingrese el salario bruto.
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="HoraEntrada">Hora de Entrada:</label>
                    <div class="input-group clockpicker">
                        @Html.TextBoxFor(model => model.HoraEntrada, new { @class = "form-control", placeholder = "Ingrese la hora de entrada", required = "required" })
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                    <div class="invalid-feedback">
                        Por favor, ingrese la hora de entrada.
                    </div>
                </div>
                <div class="form-group">
                    <label for="HoraSalida">Hora de Salida:</label>
                    <div class="input-group clockpicker">
                        @Html.TextBoxFor(model => model.HoraSalida, new { @class = "form-control", placeholder = "Ingrese la hora de salida", required = "required" })
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                    <div class="invalid-feedback">
                        Por favor, ingrese la hora de salida.
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Crear Doctor</button>
        </div>
    }

</div>

@section scripts {
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <

Views/Doctor/VerDoctor.cshtml
@model IEnumerable<G7.Models.DoctorObj>

@{
    ViewBag.Title = "VerDoctor";
}

<h2>VerDoctor</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <tr>
        <th>
            Id Doctor
        </th>
        <th>
            Id Usuario
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdDoctor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdUsuario)
            </td>
            

        </tr>
    }

</table>