Controllers/PlanillaController.cs
using System;
using G7.Models;
using System.Collections.Generic;
using System.IO;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Web;
using System.Web.Mvc;

namespace G7.Controllers
{
    public class PlanillaController : Controller
    {
        //Obtiene la información para crear una planilla
        [HttpPost]
        public ActionResult CrearPlanilla(PlanillaObj planilla)
        {
            using (HttpClient client = new HttpClient())
            {
                string rutaApi = ConfigurationManager.AppSettings["rutaApi"] + "api/Planilla/CrearPlanilla";
                string token = Session["codigoToken"]?.ToString();

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                JsonContent contenido = JsonContent.Create(planilla);

                HttpResponseMessage respuesta = client.PostAsync(rutaApi, contenido).Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    return RedirectToAction("VerPlanilla", new { id = planilla.IdPlanilla });
                }
                return View("Error");
            }
        }

        //Obtiene la información para visualizar una planilla existente
        public ActionResult VerPlanilla(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                string rutaApi = ConfigurationManager.AppSettings["rutaApi"] + "api/Planilla/VerPlanilla?id=" + id;
                string token = Session["codigoToken"]?.ToString();

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                HttpResponseMessage respuesta = client.GetAsync(rutaApi).Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    PlanillaObj planilla = respuesta.Content.ReadAsAsync<PlanillaObj>().Result;
                    return View(planilla);
                }
                return View("Error");
            }
        }

        //Obtiene la información para editar una planilla existente
        [HttpPost]
        public ActionResult EditarPlanilla(PlanillaObj planilla)
        {
            RespuestaPlanillaObj resultado = EditarPlanillaModel(planilla);

            if (resultado != null && resultado.Codigo == 200)
            {
                return RedirectToAction("VerPlanilla", new { id = planilla.IdPlanilla });
            }
            return View("Error");
        }

        //Elimina una planilla existente
        public ActionResult EliminarPlanilla(int id)
        {
            RespuestaPlanillaObj resultado = EliminarPlanillaModel(id);

            if (resultado != null && resultado.Codigo == 200)
            {
                return RedirectToAction("Index", "Home");
            }
            return View("Error");
        }

        private RespuestaPlanillaObj EditarPlanillaModel(PlanillaObj planilla)
        {
            using (HttpClient client = new HttpClient())
            {
                string rutaApi = ConfigurationManager.AppSettings["rutaApi"] + "api/Planilla/EditarPlanilla";
                string token = HttpContext.Session["codigoToken"].ToString();

                JsonContent contenido = JsonContent.Create(planilla);

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                HttpResponseMessage respuesta = client.PutAsync(rutaApi, contenido).Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    return respuesta.Content.ReadAsAsync<RespuestaPlanillaObj>().Result;
                }
                return null;
            }
        }
        private RespuestaPlanillaObj EliminarPlanillaModel(int idPlanilla)
        {
            using (HttpClient client = new HttpClient())
            {
                string rutaApi = ConfigurationManager.AppSettings["rutaApi"] + "api/Planilla/EliminarPlanilla?idPlanilla=" + idPlanilla;
                string token = HttpContext.Session["codigoToken"].ToString();

                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                HttpResponseMessage respuesta = client.DeleteAsync(rutaApi).Result;

                if (respuesta.IsSuccessStatusCode)
                {
                    return respuesta.Content.ReadAsAsync<RespuestaPlanillaObj>().Result;
                }
                return null;
            }
        }
    }
}

Views/Planilla/EditarPlanilla.cshtml
@model G7.Models.PlanillaObj

@{
    ViewBag.Title = "EditarPlanilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditarPlanilla</h2>
@using (Html.BeginForm("EditarPlanilla", "Planilla", FormMethod.Post))
{
    @Html.AntiForgeryToken()

}
    <div class="card">
        <div class="row">
            <div class="col-12">

                <div class="card-header">
                    <h3 class="card-title">Editar</h3>
                </div>

                <div class="card-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.HiddenFor(model => model.IdPlanilla, new { htmlAttributes = new { @class = "form-control" } })

                    @Html.HiddenFor(model => model.IdDoctor, new { htmlAttributes = new { @class = "form-control" } })

                    <div class="form-group">
                        @Html.LabelFor(model => model.HorasTrabajadas, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HorasTrabajadas, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HorasTrabajadas, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SalarioBruto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SalarioBruto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SalarioBruto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Seguro, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Seguro, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Seguro, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Deducciones, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Deducciones, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Deducciones, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SalarioNeto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SalarioNeto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SalarioNeto, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="card">
                        <div class="row">
                            <div class="col-12">

                                <div class="card-header">
                                    <h3 class="card-title">Editar</h3>
                                </div>

                                <div class="card-body">

                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                    @Html.HiddenFor(model => model.IdPlanilla, new { htmlAttributes = new { @class = "form-control" } })

                                    @Html.HiddenFor(model => model.IdDoctor, new { htmlAttributes = new { @class = "form-control" } })

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.HorasTrabajadas, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.HorasTrabajadas, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.HorasTrabajadas, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SalarioBruto, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.SalarioBruto, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.SalarioBruto, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Seguro, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Seguro, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Seguro, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Deducciones, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.Deducciones, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.Deducciones, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.SalarioNeto, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.SalarioNeto, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.SalarioNeto, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

Views/Planilla/MostrarPlanilla.cshtml
@model IEnumerable<G7.Models.PlanillaObj>

@{
    ViewBag.Title = "MostrarPlanilla";
}

<h2>MostrarPlanilla</h2>

<p>
    @Html.ActionLink("Registrar Planilla", "RegistrarPlanilla", "Planilla", null, new { @class = "btn btn-dark" })
</p>
<br>
<br>
<table class="table">
    <tr>
        <th>
            IdPlanilla
        </th>
        <th>
            IdDoctor
        </th>
        <th>
            Horas Trabajadas
        </th>
        <th>
            Salario Bruto
        </th>
        <th>
            Seguro
        </th>
        <th>
            Deducciones
        </th>
        <th>
            Salario Neto
        </th>
        <th>
            Acciones
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPlanilla)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdDoctor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HorasTrabajadas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalarioBruto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Seguro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deducciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalarioNeto)
            </td>
            <td>
                @Html.ActionLink("Editar", "EditarPlanilla", "Planilla", new { id = item.IdPlanilla }, new { @class = "btn btn-secondary" })
            </td>
        </tr>
    }

</table>

Views/Planilla/RegistrarPlanilla.cshtml
@model G7.Models.PlanillaObj

@{
    ViewBag.Title = "RegistrarPlanilla";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Planilla</h2>

@using (Html.BeginForm("RegistrarPlanilla", "Planilla", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="card">
        <div class="row">
            <div class="col-12">

                <div class="card-header">
                    <h3 class="card-title">Registrar</h3>
                </div>

                <div class="card-body">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.IdDoctor, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.IdDoctor, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.IdDoctor, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.HorasTrabajadas, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.HorasTrabajadas, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.HorasTrabajadas, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SalarioBruto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SalarioBruto, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SalarioBruto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Seguro, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Seguro, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Seguro, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Deducciones, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Deducciones, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Deducciones, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.SalarioNeto, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SalarioNeto, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.SalarioNeto, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            <a href="@Url.Action("Index", "Planilla")" class="btn btn-default">Cancelar</a>
                        </div>
                    </div>
                    }

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }

Views/Planilla/VerPlanilla.cshtml
@model IEnumerable<G7.Models.PlanillaObj>

@{
    ViewBag.Title = "VerPlanilla";
}

<h2>VerPlanilla</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
    <tr>
        <th>
            Id planilla
        </th>
        <th>
            Id Doctor
        </th>
        <th>
            Horas trabajadas al mes
        </th>
        <th>
            Salario bruto
        </th>
        <th>
            Seguro
        </th>
        <th>
            Deducciones
        </th>
        <th>
            Salario neto
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdPlanilla)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdDoctor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HorasTrabajadas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalarioBruto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Seguro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Deducciones)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalarioNeto)
            </td>
            
        </tr>
    }

</table>